### ISSUE TITLE
NodeBots Nigeria

### ISSUE THREAD

**Issue by oyedotunsodiq045** [nodebots/nodebots.io#101]

**Comment by asoluwaseun** [comment]
Are you interested in starting a NodeBots's club Nigeria?

**Comment by oyedotunsodiq045** [comment]
> Are you interested in starting a NodeBots's club Nigeria?

Yeah I've started it and will soon be releasing tutorial on Setting up a Project Working Area and Building a basic project with the Tessel 2 and Johnny Five, then we can move on to setting up a webinar.
