### ISSUE TITLE
502 on forums.nodebots.io

### ISSUE THREAD

**Issue by kosamari** [nodebots/nodebots.io#32]
http://forums.nodebots.io is giving me "502 Bad Gateway" error from nginx.  I found http://forum.nodebots.io is a working link, but seems to be pointed to same page as http://blog.nodebots.io .

Where would be the best place for forum/discussion on nodebots ??

**Comment by voodootikigod** [comment]
It seems to have fallen over, will bring it back up sorry.

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.

**Comment by kosamari** [comment]
Its back up ! thank you so much :+1:
